---
name: Mirror and run GitLab CI
true:
  - push
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}
jobs:
  build:
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    runs-on: ubuntu-latest
    steps:
      - if: always()
        uses: act10ns/slack@v1
        with:
          channel: '#ansible'
          message: Starting buluma.checkmk_agent GitLab Trigger...
          status: starting
      - uses: actions/checkout@v6
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_HOSTNAME: gitlab.com
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: 3340722x
          GITLAB_USERNAME: buluma
        name: Mirror + trigger CI
        uses: buluma/gitlab-mirror-ci-action@1.0.7
        with:
          args: buluma/ansible-role-checkmk_agent
      - if: always()
        name: Slack Notification
        uses: act10ns/slack@v1
        with:
          channel: '#ansible'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
